version: '3'
services:
  web:
    env_file:
      - .env
    container_name: anon-blog-server
    restart: always
    build: .
    ports:
      - '80:5000'
    external_links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'