name: anon-blog-server CI

on: [push]

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup node
      uses: actions/setup-node@v1
      with:
        node-version: 12

    - name: Setup env
      uses: c-py/action-dotenv-to-setenv@v2
      with:
        env-file: .env

    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.3.0
      with:
        mongodb-version: 4.4

    - run: npm install
    - run: npm run build --if-present
    - run: npm test
      env:
        CI: true
        SERVER_IP: ${{ secrets.SERVER_IP }}
        SERVER_USERNAME: ${{ secrets.SERVER_USERNAME }}
        SERVER_PASSWORD: ${{ secrets.SERVER_PASSWORD }}

    - name: deploying via ssh
      uses: appleboy/ssh-action@master
      with:
        host: $SERVER_IP
        username: $SERVER_USERNAME
        password: $SERVER_PASSWORD
        script: |
          cd anon-blog-server
          git pull origin master
          docker-compose down
          docker-compose up -d
