name: Node.js CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup node
      uses: actions/setup-node@v1
      with:
        node-version: 12

    - name: Setup env
      uses: c-py/action-dotenv-to-setenv@v2
      with:
        env-file: .env

    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.3.0
      with:
        mongodb-version: 4.4

    - run: npm install
    - run: npm run build --if-present
    - run: npm test
      env:
        CI: true