name: anon-blog-server CI

on: [push]

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup node
      uses: actions/setup-node@v1
      with:
        node-version: 12

    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.3.0
      with:
        mongodb-version: 4.4

    - run: npm install
    - run: npm run build --if-present
    - run: npm test
      env:
        CI: true

    - name: deploying via ssh
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USERNAME }}
        password: ${{ secrets.SERVER_PASSWORD }}
        script: |
          cd anon-blog-server
          git pull origin master
          docker-compose down
          docker-compose rm -f
          docker-compose build
          docker-compose up -d
